/////////////////////////////////////////////////////////////////////////////
// $Id: SessionProperties_symbols.h 883 2004-11-04 21:15:18Z felfert $
//
// Purpose:     Symbols file
// Author:      Fritz Elfert
// Created:     11/04/04 06:34:40
// Copyright:   Copyright 2004 Millenux GmbH
// Licence:     LGPL
/////////////////////////////////////////////////////////////////////////////

#define ID_DIALOG_PROPERTIES_SYMBOL_0 _("Session properties - MXclient")
#define ID_DIALOG_PROPERTIES_SYMBOL_1 _("General")
#define ID_DIALOG_PROPERTIES_SYMBOL_2 _("Server")
#define ID_DIALOG_PROPERTIES_SYMBOL_3 _("Host")
#define ID_DIALOG_PROPERTIES_SYMBOL_4 _("Port")
#define ID_DIALOG_PROPERTIES_SYMBOL_5 _("Remember my password")
#define ID_DIALOG_PROPERTIES_SYMBOL_6 _("Use SmartCard")
#define ID_DIALOG_PROPERTIES_SYMBOL_7 _("Desktop")
#define ID_DIALOG_PROPERTIES_SYMBOL_8 _("Unix")
#define ID_DIALOG_PROPERTIES_SYMBOL_9 _("Windows")
#define ID_DIALOG_PROPERTIES_SYMBOL_10 _("VNC")
#define ID_DIALOG_PROPERTIES_SYMBOL_11 _("KDE")
#define ID_DIALOG_PROPERTIES_SYMBOL_12 _("GNOME")
#define ID_DIALOG_PROPERTIES_SYMBOL_13 _("CDE")
#define ID_DIALOG_PROPERTIES_SYMBOL_14 _("XFCE")
#define ID_DIALOG_PROPERTIES_SYMBOL_15 _("Custom")
#define ID_DIALOG_PROPERTIES_SYMBOL_16 _("Settings...")
#define ID_DIALOG_PROPERTIES_SYMBOL_17 _("MODEM")
#define ID_DIALOG_PROPERTIES_SYMBOL_18 _("ISDN")
#define ID_DIALOG_PROPERTIES_SYMBOL_19 _("ADSL")
#define ID_DIALOG_PROPERTIES_SYMBOL_20 _("WAN")
#define ID_DIALOG_PROPERTIES_SYMBOL_21 _("LAN")
#define ID_DIALOG_PROPERTIES_SYMBOL_22 _("Display")
#define ID_DIALOG_PROPERTIES_SYMBOL_23 _("640x480")
#define ID_DIALOG_PROPERTIES_SYMBOL_24 _("800x600")
#define ID_DIALOG_PROPERTIES_SYMBOL_25 _("1024x768")
#define ID_DIALOG_PROPERTIES_SYMBOL_26 _("Available Area")
#define ID_DIALOG_PROPERTIES_SYMBOL_27 _("Fullscreen")
#define ID_DIALOG_PROPERTIES_SYMBOL_28 _("W")
#define ID_DIALOG_PROPERTIES_SYMBOL_29 _("H")
#define ID_DIALOG_PROPERTIES_SYMBOL_30 _("Use default image encoding")
#define ID_DIALOG_PROPERTIES_SYMBOL_31 _("Use custom settings")
#define ID_DIALOG_PROPERTIES_SYMBOL_32 _("Modify")
#define ID_DIALOG_PROPERTIES_SYMBOL_33 _("Advanced")
#define ID_DIALOG_PROPERTIES_SYMBOL_34 _("Network")
#define ID_DIALOG_PROPERTIES_SYMBOL_35 _("Disable no-delay on TCP connection")
#define ID_DIALOG_PROPERTIES_SYMBOL_36 _("Disable ZLIB stream compression")
#define ID_DIALOG_PROPERTIES_SYMBOL_37 _("Enable SSL encryption of all traffic")
#define ID_DIALOG_PROPERTIES_SYMBOL_38 _("Cache")
#define ID_DIALOG_PROPERTIES_SYMBOL_39 _("In memory")
#define ID_DIALOG_PROPERTIES_SYMBOL_40 _("1 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_41 _("2 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_42 _("4 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_43 _("8 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_44 _("16 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_45 _("32 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_46 _("On disk")
#define ID_DIALOG_PROPERTIES_SYMBOL_47 _("0 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_48 _("64 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_49 _("128 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_50 _("Clean all cache files")
#define ID_DIALOG_PROPERTIES_SYMBOL_51 _("Backingstore")
#define ID_DIALOG_PROPERTIES_SYMBOL_52 _("Keyboard")
#define ID_DIALOG_PROPERTIES_SYMBOL_53 _("Keep current keyboard settings")
#define ID_DIALOG_PROPERTIES_SYMBOL_54 _("Use other layout")
#define ID_DIALOG_PROPERTIES_SYMBOL_55 _("Afrikaans")
#define ID_DIALOG_PROPERTIES_SYMBOL_56 _("Albanian")
#define ID_DIALOG_PROPERTIES_SYMBOL_57 _("Arabic")
#define ID_DIALOG_PROPERTIES_SYMBOL_58 _("Basque")
#define ID_DIALOG_PROPERTIES_SYMBOL_59 _("Belarusian")
#define ID_DIALOG_PROPERTIES_SYMBOL_60 _("Bulgarian")
#define ID_DIALOG_PROPERTIES_SYMBOL_61 _("Catalan")
#define ID_DIALOG_PROPERTIES_SYMBOL_62 _("Chinese")
#define ID_DIALOG_PROPERTIES_SYMBOL_63 _("Croatian")
#define ID_DIALOG_PROPERTIES_SYMBOL_64 _("Czech")
#define ID_DIALOG_PROPERTIES_SYMBOL_65 _("Danish")
#define ID_DIALOG_PROPERTIES_SYMBOL_66 _("Dutch")
#define ID_DIALOG_PROPERTIES_SYMBOL_67 _("English (GB)")
#define ID_DIALOG_PROPERTIES_SYMBOL_68 _("English (US)")
#define ID_DIALOG_PROPERTIES_SYMBOL_69 _("Estonian")
#define ID_DIALOG_PROPERTIES_SYMBOL_70 _("Faeorese")
#define ID_DIALOG_PROPERTIES_SYMBOL_71 _("Farsi")
#define ID_DIALOG_PROPERTIES_SYMBOL_72 _("Finnish")
#define ID_DIALOG_PROPERTIES_SYMBOL_73 _("French")
#define ID_DIALOG_PROPERTIES_SYMBOL_74 _("German")
#define ID_DIALOG_PROPERTIES_SYMBOL_75 _("Greek")
#define ID_DIALOG_PROPERTIES_SYMBOL_76 _("Hebrew")
#define ID_DIALOG_PROPERTIES_SYMBOL_77 _("Hungarian")
#define ID_DIALOG_PROPERTIES_SYMBOL_78 _("Icelandic")
#define ID_DIALOG_PROPERTIES_SYMBOL_79 _("Indonesian")
#define ID_DIALOG_PROPERTIES_SYMBOL_80 _("Italian")
#define ID_DIALOG_PROPERTIES_SYMBOL_81 _("Japanese")
#define ID_DIALOG_PROPERTIES_SYMBOL_82 _("Korean")
#define ID_DIALOG_PROPERTIES_SYMBOL_83 _("Latvian")
#define ID_DIALOG_PROPERTIES_SYMBOL_84 _("Lithuanian")
#define ID_DIALOG_PROPERTIES_SYMBOL_85 _("Norwegian")
#define ID_DIALOG_PROPERTIES_SYMBOL_86 _("Polish")
#define ID_DIALOG_PROPERTIES_SYMBOL_87 _("Portugese")
#define ID_DIALOG_PROPERTIES_SYMBOL_88 _("Romanian")
#define ID_DIALOG_PROPERTIES_SYMBOL_89 _("Russian")
#define ID_DIALOG_PROPERTIES_SYMBOL_90 _("Slovak")
#define ID_DIALOG_PROPERTIES_SYMBOL_91 _("Slovenian")
#define ID_DIALOG_PROPERTIES_SYMBOL_92 _("Spanish")
#define ID_DIALOG_PROPERTIES_SYMBOL_93 _("Swedish")
#define ID_DIALOG_PROPERTIES_SYMBOL_94 _("Thai")
#define ID_DIALOG_PROPERTIES_SYMBOL_95 _("Turkish")
#define ID_DIALOG_PROPERTIES_SYMBOL_96 _("Vietnamese")
#define ID_DIALOG_PROPERTIES_SYMBOL_97 _("Services")
#define ID_DIALOG_PROPERTIES_SYMBOL_98 _("Enable printer and file sharing")
#define ID_DIALOG_PROPERTIES_SYMBOL_99 _("Add")
#define ID_DIALOG_PROPERTIES_SYMBOL_100 _("Delete")
#define ID_DIALOG_PROPERTIES_SYMBOL_101 _("Enable multimedia support")
#define ID_DIALOG_PROPERTIES_SYMBOL_102 _("Environment")
#define ID_DIALOG_PROPERTIES_SYMBOL_103 _("User MX directory")
#define ID_DIALOG_PROPERTIES_SYMBOL_104 _("...")
#define ID_DIALOG_PROPERTIES_SYMBOL_105 _("Remove old session files")
#define ID_DIALOG_PROPERTIES_SYMBOL_106 _("System MX directory")
#define ID_DIALOG_PROPERTIES_SYMBOL_107 _("Font server")
#define ID_DIALOG_PROPERTIES_SYMBOL_108 _("Use font server")
#define ID_DIALOG_PROPERTIES_SYMBOL_109 _("Select MX fonts")
#define ID_DIALOG_PROPERTIES_SYMBOL_110 _("Default")
#define ID_DIALOG_PROPERTIES_SYMBOL_111 _("Font")
#define ID_DIALOG_PROPERTIES_SYMBOL_112 _("Fixed")
#define ID_DIALOG_PROPERTIES_SYMBOL_113 _("About")
#define ID_DIALOG_PROPERTIES_SYMBOL_114 _("&Delete")
#define ID_DIALOG_PROPERTIES_SYMBOL_115 _("&Apply")
#define ID_DIALOG_PROPERTIES_SYMBOL_116 _("&OK")
#define ID_DIALOG_PROPERTIES_SYMBOL_117 _("&Cancel")
