/////////////////////////////////////////////////////////////////////////////
// $Id$
//
// Purpose:     Symbols file
// Author:      Fritz Elfert
// Created:     Thu 07 Dec 2006 05:20:38 CET
// Copyright:   Copyright 2004 Millenux GmbH, 2006 InnoviData GmbH
// Licence:     LGPL
/////////////////////////////////////////////////////////////////////////////

#define ID_DIALOG_PROPERTIES_SYMBOL_0 _("Session properties - MXclient")
#define ID_DIALOG_PROPERTIES_SYMBOL_1 _("General")
#define ID_DIALOG_PROPERTIES_SYMBOL_2 _("Server")
#define ID_DIALOG_PROPERTIES_SYMBOL_3 _("Host")
#define ID_DIALOG_PROPERTIES_SYMBOL_4 _("Port")
#define ID_DIALOG_PROPERTIES_SYMBOL_5 _("Remember my password")
#define ID_DIALOG_PROPERTIES_SYMBOL_6 _("Key...")
#define ID_DIALOG_PROPERTIES_SYMBOL_7 _("Use SmartCard")
#define ID_DIALOG_PROPERTIES_SYMBOL_8 _("Desktop")
#define ID_DIALOG_PROPERTIES_SYMBOL_9 _("Unix")
#define ID_DIALOG_PROPERTIES_SYMBOL_10 _("Windows")
#define ID_DIALOG_PROPERTIES_SYMBOL_11 _("VNC")
#define ID_DIALOG_PROPERTIES_SYMBOL_12 _("KDE")
#define ID_DIALOG_PROPERTIES_SYMBOL_13 _("GNOME")
#define ID_DIALOG_PROPERTIES_SYMBOL_14 _("CDE")
#define ID_DIALOG_PROPERTIES_SYMBOL_15 _("XFCE")
#define ID_DIALOG_PROPERTIES_SYMBOL_16 _("Custom")
#define ID_DIALOG_PROPERTIES_SYMBOL_17 _("Settings...")
#define ID_DIALOG_PROPERTIES_SYMBOL_18 _("MODEM")
#define ID_DIALOG_PROPERTIES_SYMBOL_19 _("ISDN")
#define ID_DIALOG_PROPERTIES_SYMBOL_20 _("ADSL")
#define ID_DIALOG_PROPERTIES_SYMBOL_21 _("WAN")
#define ID_DIALOG_PROPERTIES_SYMBOL_22 _("LAN")
#define ID_DIALOG_PROPERTIES_SYMBOL_23 _("Display")
#define ID_DIALOG_PROPERTIES_SYMBOL_24 _("640x480")
#define ID_DIALOG_PROPERTIES_SYMBOL_25 _("800x600")
#define ID_DIALOG_PROPERTIES_SYMBOL_26 _("1024x768")
#define ID_DIALOG_PROPERTIES_SYMBOL_27 _("Available Area")
#define ID_DIALOG_PROPERTIES_SYMBOL_28 _("Fullscreen")
#define ID_DIALOG_PROPERTIES_SYMBOL_29 _("W")
#define ID_DIALOG_PROPERTIES_SYMBOL_30 _("H")
#define ID_DIALOG_PROPERTIES_SYMBOL_31 _("Use default image encoding")
#define ID_DIALOG_PROPERTIES_SYMBOL_32 _("Use custom settings")
#define ID_DIALOG_PROPERTIES_SYMBOL_33 _("Modify...")
#define ID_DIALOG_PROPERTIES_SYMBOL_34 _("Advanced")
#define ID_DIALOG_PROPERTIES_SYMBOL_35 _("Network")
#define ID_DIALOG_PROPERTIES_SYMBOL_36 _("Disable no-delay on TCP connection")
#define ID_DIALOG_PROPERTIES_SYMBOL_37 _("Disable ZLIB stream compression")
#define ID_DIALOG_PROPERTIES_SYMBOL_38 _("Enable SSL encryption of all traffic")
#define ID_DIALOG_PROPERTIES_SYMBOL_39 _("Connect through HTTP proxy")
#define ID_DIALOG_PROPERTIES_SYMBOL_40 _("Cache")
#define ID_DIALOG_PROPERTIES_SYMBOL_41 _("In memory")
#define ID_DIALOG_PROPERTIES_SYMBOL_42 _("0 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_43 _("1 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_44 _("2 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_45 _("4 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_46 _("8 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_47 _("16 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_48 _("32 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_49 _("On disk")
#define ID_DIALOG_PROPERTIES_SYMBOL_50 _("64 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_51 _("128 Mb")
#define ID_DIALOG_PROPERTIES_SYMBOL_52 _("Clean all cache files")
#define ID_DIALOG_PROPERTIES_SYMBOL_53 _("Keyboard")
#define ID_DIALOG_PROPERTIES_SYMBOL_54 _("Keep current keyboard settings")
#define ID_DIALOG_PROPERTIES_SYMBOL_55 _("Use other layout")
#define ID_DIALOG_PROPERTIES_SYMBOL_56 _("Afrikaans")
#define ID_DIALOG_PROPERTIES_SYMBOL_57 _("Albanian")
#define ID_DIALOG_PROPERTIES_SYMBOL_58 _("Arabic")
#define ID_DIALOG_PROPERTIES_SYMBOL_59 _("Basque")
#define ID_DIALOG_PROPERTIES_SYMBOL_60 _("Belarusian")
#define ID_DIALOG_PROPERTIES_SYMBOL_61 _("Bulgarian")
#define ID_DIALOG_PROPERTIES_SYMBOL_62 _("Catalan")
#define ID_DIALOG_PROPERTIES_SYMBOL_63 _("Chinese")
#define ID_DIALOG_PROPERTIES_SYMBOL_64 _("Croatian")
#define ID_DIALOG_PROPERTIES_SYMBOL_65 _("Czech")
#define ID_DIALOG_PROPERTIES_SYMBOL_66 _("Danish")
#define ID_DIALOG_PROPERTIES_SYMBOL_67 _("Dutch")
#define ID_DIALOG_PROPERTIES_SYMBOL_68 _("English (GB)")
#define ID_DIALOG_PROPERTIES_SYMBOL_69 _("English (US)")
#define ID_DIALOG_PROPERTIES_SYMBOL_70 _("Estonian")
#define ID_DIALOG_PROPERTIES_SYMBOL_71 _("Faeorese")
#define ID_DIALOG_PROPERTIES_SYMBOL_72 _("Farsi")
#define ID_DIALOG_PROPERTIES_SYMBOL_73 _("Finnish")
#define ID_DIALOG_PROPERTIES_SYMBOL_74 _("French")
#define ID_DIALOG_PROPERTIES_SYMBOL_75 _("German")
#define ID_DIALOG_PROPERTIES_SYMBOL_76 _("Greek")
#define ID_DIALOG_PROPERTIES_SYMBOL_77 _("Hebrew")
#define ID_DIALOG_PROPERTIES_SYMBOL_78 _("Hungarian")
#define ID_DIALOG_PROPERTIES_SYMBOL_79 _("Icelandic")
#define ID_DIALOG_PROPERTIES_SYMBOL_80 _("Indonesian")
#define ID_DIALOG_PROPERTIES_SYMBOL_81 _("Italian")
#define ID_DIALOG_PROPERTIES_SYMBOL_82 _("Japanese")
#define ID_DIALOG_PROPERTIES_SYMBOL_83 _("Korean")
#define ID_DIALOG_PROPERTIES_SYMBOL_84 _("Latvian")
#define ID_DIALOG_PROPERTIES_SYMBOL_85 _("Lithuanian")
#define ID_DIALOG_PROPERTIES_SYMBOL_86 _("Norwegian")
#define ID_DIALOG_PROPERTIES_SYMBOL_87 _("Polish")
#define ID_DIALOG_PROPERTIES_SYMBOL_88 _("Portugese")
#define ID_DIALOG_PROPERTIES_SYMBOL_89 _("Romanian")
#define ID_DIALOG_PROPERTIES_SYMBOL_90 _("Russian")
#define ID_DIALOG_PROPERTIES_SYMBOL_91 _("Slovak")
#define ID_DIALOG_PROPERTIES_SYMBOL_92 _("Slovenian")
#define ID_DIALOG_PROPERTIES_SYMBOL_93 _("Spanish")
#define ID_DIALOG_PROPERTIES_SYMBOL_94 _("Swedish")
#define ID_DIALOG_PROPERTIES_SYMBOL_95 _("Thai")
#define ID_DIALOG_PROPERTIES_SYMBOL_96 _("Turkish")
#define ID_DIALOG_PROPERTIES_SYMBOL_97 _("Vietnamese")
#define ID_DIALOG_PROPERTIES_SYMBOL_98 _("Services")
#define ID_DIALOG_PROPERTIES_SYMBOL_99 _("Enable SMB printer and file sharing")
#define ID_DIALOG_PROPERTIES_SYMBOL_100 _("Enable CUPS printing")
#define ID_DIALOG_PROPERTIES_SYMBOL_101 _("Add")
#define ID_DIALOG_PROPERTIES_SYMBOL_102 _("Modify")
#define ID_DIALOG_PROPERTIES_SYMBOL_103 _("Delete")
#define ID_DIALOG_PROPERTIES_SYMBOL_104 _("Enable multimedia support")
#define ID_DIALOG_PROPERTIES_SYMBOL_105 _("Environment")
#define ID_DIALOG_PROPERTIES_SYMBOL_106 _("User MX directory")
#define ID_DIALOG_PROPERTIES_SYMBOL_107 _("...")
#define ID_DIALOG_PROPERTIES_SYMBOL_108 _("Remove old session files")
#define ID_DIALOG_PROPERTIES_SYMBOL_109 _("System MX directory")
#define ID_DIALOG_PROPERTIES_SYMBOL_110 _("System CUPS daemon")
#define ID_DIALOG_PROPERTIES_SYMBOL_111 _("Select MX fonts")
#define ID_DIALOG_PROPERTIES_SYMBOL_112 _("Default")
#define ID_DIALOG_PROPERTIES_SYMBOL_113 _("Font")
#define ID_DIALOG_PROPERTIES_SYMBOL_114 _("Fixed")
#define ID_DIALOG_PROPERTIES_SYMBOL_115 _("About")
#define ID_DIALOG_PROPERTIES_SYMBOL_116 _("&Delete")
#define ID_DIALOG_PROPERTIES_SYMBOL_117 _("&Apply")
#define ID_DIALOG_PROPERTIES_SYMBOL_118 _("&OK")
#define ID_DIALOG_PROPERTIES_SYMBOL_119 _("&Cancel")
