#!/bin/sh

set -e

BUILDDIR=`pwd`
cd `dirname $0`/../..
TOPSRC=`pwd`
cd $BUILDDIR
if test -z "$DEST" ; then
    DEST=$BUILDDIR/dist
fi
if test -z "$PFX" ; then
    PFX=/Library/OpenNX
fi
ALLPKG="nxcomp nxcompsh nxproxy nxservice nxesd nxssh"
$TOPSRC/getnxsrcpkg $ALLPKG
for pkg in $ALLPKG ; do
    tar xzf ${pkg}-*.tar.gz
done

for pkg in nxcomp nxcompsh nxproxy nxservice nxesd ; do
    cd $pkg
    for p in $TOPSRC/patches/${pkg}-*.patch ; do
        echo === Applying `basename $p` in $pkg
        patch -p1 < $p
    done
    autoreconf -f -i
    ./configure --prefix=$PFX
    make
    make DESTDIR=$DEST install
    cd ..
    echo === Build of $pkg complete
done

cd nxssh
patch -p1 < $TOPSRC/patches/openssh-scard-pin.patch
autoreconf -f -i
./configure --prefix=$PFX \
  --with-opensc=$BUILDDIR/../scbuild/dist$PFX \
  --with-ssl-dir=/Library/OpenSC \
  --with-cflags="-arch i386 -arch ppc" \
  --with-ldflags="-arch i386 -arch ppc -L$DEST$PFX/lib"
make
cp nxssh $DEST$PFX/bin/nxssh
cd ..

rm -rf $DEST$PFX/{include,etc,share} \
       $DEST$PFX/lib/*.la \
       $DEST$PFX/lib/*.a \
       $DEST$PFX/lib/pkgconfig \
       $DEST$PFX/bin/esd*
