#!/bin/sh

set -e

BUILDDIR=`pwd`
cd `dirname $0`/../..
TOPSRC=`pwd`
cd $BUILDDIR
if test -z "$DEST" ; then
    DEST=$BUILDDIR/dist
fi
if test -z "$PFX" ; then
    PFX=/Library/OpenNX
fi
ALLPKG="nxcomp nxproxy nxesd nxssh"
$TOPSRC/getnxsrcpkg $ALLPKG
for pkg in $ALLPKG ; do
    tar xzf ${pkg}-*.tar.gz
done

test -f audiofile-0.2.6.tar.gz || wget http://www.68k.org/~michael/audiofile/audiofile-0.2.6.tar.gz
tar xzf audiofile-0.2.6.tar.gz
cd audiofile-0.2.6
autoreconf -f -i
CFLAGS="-arch i386 -arch ppc" LDFLAGS="-arch i386 -arch ppc" ./configure \
        --prefix=$PFX --disable-static --disable-dependency-tracking
make DESTDIR=$DEST install
cd ..

for pkg in nxcomp nxproxy nxesd ; do
    cd $pkg
    for p in $TOPSRC/patches/${pkg}-*.patch ; do
        echo === Applying `basename $p` in $pkg
        patch -p1 < $p
    done
    autoreconf -f -i
    cargs=
    margs=
    case $pkg in
        nxesd)
            cargs="--disable-audiofiletest --with-audiofile=yes"
            margs="AUDIOFILE_CFLAGS=\"-I$DEST$PFX/include\" LDFLAGS=\"-L$DEST$PFX/lib\" LIBS=-laudiofile"
            ;;
    esac
    ./configure --prefix=$PFX $cargs
    echo make $margs
    make $margs
    make DESTDIR=$DEST $margs install
    cd ..
    echo === Build of $pkg complete
done

cd nxssh
patch -p1 < $TOPSRC/patches/openssh-scard-pin.patch
patch -p1 < $TOPSRC/patches/nxssh-dynopensc.patch
autoreconf -f -i
LDFLAGS="-L$DEST$PFX/lib" \
./configure --prefix=$PFX \
  --with-opensc=$BUILDDIR/../scbuild/dist$PFX \
  --enable-opensc-dynamic \
  --with-cflags="-arch i386 -arch ppc" \
  --with-ldflags="-arch i386 -arch ppc"
make
cp nxssh $DEST$PFX/bin/nxssh
cd ..

rm -rf $DEST$PFX/{include,etc,share} \
       $DEST$PFX/lib/*.la \
       $DEST$PFX/lib/*.a \
       $DEST$PFX/lib/pkgconfig \
       $DEST$PFX/bin/esd*
