#!/bin/sh

set -e

SV=0.9.8k
V=0.11.9
D=`pwd`

if [ $# != 2 ] ; then
    echo "Usage: buildopensc <prefix> <libdir>" >&2
    exit 1
fi
PFX=$1
LIBDEST=$2

wget http://www.opensc-project.org/files/opensc/opensc-$V.tar.gz
rm -rf opensc-$V
tar xzf opensc-$V.tar.gz
cd opensc-$V
OPENSSL_CFLAGS="-I$D/dist$PFX/include" \
OPENSSL_LIBS="-L$D/dist$PFX/lib -lcrypto" \
CFLAGS="-arch ppc -arch i386" \
LDLAGS="-arch ppc -arch i386" \
./configure \
        --prefix=$PFX \
        --enable-pcsc \
        --sysconfdir=/Library/OpenSC/etc \
        --disable-static \
        --disable-dependency-tracking
make
rm -rf $D/dist
mkdir $D/dist
make DESTDIR=$D/dist install
mkdir -p $LIBDEST
cp -av $D/dist$PFX/lib/* $LIBDEST
