#!/bin/sh
if test -e /Library/Receipts/OpenNX.pkg ; then
    (
        # let applescript terminate gracefully
        sleep 5
        rm -rf /Library/OpenNX
        rm -rf /Applications/OpenNX
        rm -rf /Library/Receipts/OpenNX.pkg
    ) &
fi
